### ISSUE TITLE
Couldn't get the example "provided.al2" for GoLang working

### ISSUE THREAD

**Issue by peterpham** [aws-samples/sessions-with-aws-sam#4]
**Description**

I tried to check out the go-al2 example at https://github.com/aws-samples/sessions-with-aws-sam/tree/master/go-al2
But it failed when running `sam build`

```
$ sam build --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
No Parameters detected in the template
1 resources found in the template
Found Serverless function with name='HelloWorldFunction' and CodeUri='hello-world/'
No Parameters detected in the template
Building function 'HelloWorldFunction'
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'CustomMakeBuilder' to support capabilities 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Running workflow 'CustomMakeBuilder'
Running CustomMakeBuilder:CopySource
CustomMakeBuilder:CopySource succeeded
Running CustomMakeBuilder:MakeBuild
Current Artifacts Directory : /Users/phampp/go/src/go-al2/.aws-sam/build/HelloWorldFunction
executing Make: ['make', '--makefile', '/Users/phampp/go/src/go-al2/hello-world/Makefile', 'build-HelloWorldFunction']
CustomMakeBuilder:MakeBuild failed
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.1.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflows/custom_make/actions.py", line 94, in execute
    cwd=self.scratch_dir,
  File "/usr/local/Cellar/aws-sam-cli/1.1.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflows/custom_make/make.py", line 88, in run
    raise MakeExecutionError(message=err.decode("utf8").strip())
aws_lambda_builders.workflows.custom_make.make.MakeExecutionError: Make Failed: cp: hello-world: No such file or directory
make: *** [build-HelloWorldFunction] Error 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.1.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/Cellar/aws-sam-cli/1.1.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflows/custom_make/actions.py", line 97, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: Make Failed: cp: hello-world: No such file or directory
make: *** [build-HelloWorldFunction] Error 1

Build Failed
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 4395, 'exitReason': 'WorkflowFailedError', 'exitCode': 1, 'requestId': '62b345ee-610b-4ffa-b679-7331056509a7', 'installationId': '1355e8b0-9682-46b1-a8c8-8681022f2b0b', 'sessionId': 'a884f460-c2c9-471f-96f1-2613661bfc85', 'executionEnvironment': 'CLI', 'pyversion': '3.7.8', 'samcliVersion': '1.1.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: CustomMakeBuilder:MakeBuild - Make Failed: cp: hello-world: No such file or directory
make: *** [build-HelloWorldFunction] Error 1
```

SAM Version: SAM CLI, version 1.1.0
Mac OS 10.14.6

**Comment by peterpham** [comment]
After adding the file `go.mod` I was able to deploy.  This file was not included in the sample code.
